# Pandas Case Study

#### This dataset is Cereals Production data from the year 1961 to 2019, and it was taken from FAOSTAT (Food and Agriculture Organization of the United Nations). In the following step by step procesdure, I am going to use Pandas and NumPy libraries to perform data anaylsis and data manipulation on this dataset.

First step is to import the following libraries:

In [1]:
import pandas as pd
import numpy as np

Reading Data from a CSV file

In [2]:
usa_cereals = pd.read_csv("FAOSTAT_data_USA.csv")
usa_cereals.head(3)

FileNotFoundError: [Errno 2] No such file or directory: 'FAOSTAT_data_USA.csv'

Showing basic statistics and summary

In [16]:
usa_cereals.describe()

,Area Code,Element Code,Item Code,Year Code,Year,Value
count,180.0,180.000000,180.0,180.000000,180.000000,1.800000e+02
mean,231.0,5413.666667,1717.0,1990.500000,1990.500000,1.235340e+08
std,0.0,81.146808,0.0,17.366409,17.366409,1.427124e+08
min,231.0,5312.000000,1717.0,1961.000000,1961.000000,2.522300e+04
25%,231.0,5312.000000,1717.0,1975.750000,1975.750000,6.438125e+04
50%,231.0,5419.000000,1717.0,1990.500000,1990.500000,6.076251e+07
75%,231.0,5510.000000,1717.0,2005.250000,2005.250000,2.376391e+08
max,231.0,5510.000000,1717.0,2020.000000,2020.000000,5.034661e+08

Dropping few columns and making new dataset and assigning the new dataset to a variable "a"

In [24]:
a = usa_cereals.drop(["Domain Code", "Element Code", "Year Code", "Domain", "Area Code", "Item Code", "Unit"], axis=1)

In [25]:
a

,Area,Element,Item,Year,Value,Flag,Flag Description
0,United States of America,Area harvested,"Cereals, Total",1961,64869558,A,"Aggregate, may include official, semi-official..."
1,United States of America,Yield,"Cereals, Total",1961,25223,Fc,Calculated data
2,United States of America,Production,"Cereals, Total",1961,163619978,A,"Aggregate, may include official, semi-official..."
3,United States of America,Area harvested,"Cereals, Total",1962,60548008,A,"Aggregate, may include official, semi-official..."
4,United States of America,Yield,"Cereals, Total",1962,26831,Fc,Calculated data
...,...,...,...,...,...,...,...
175,United States of America,Yield,"Cereals, Total",2019,80056,Fc,Calculated data
176,United States of America,Production,"Cereals, Total",2019,420873484,A,"Aggregate, may include official, semi-official..."
177,United States of America,Area harvested,"Cereals, Total",2020,53195570,A,"Aggregate, may include official, semi-official..."
178,United States of America,Yield,"Cereals, Total",2020,81750,Fc,Calculated data
179,United States of America,Production,"Cereals, Total",2020,434875197,A,"Aggregate, may include official, semi-official..."

Finding the mean production per year associated with the element category.

In [26]:
a.groupby(["Element", "Year"]).mean()

                          Value
Element        Year
Area harvested 1961  64869558.0
               1962  60548008.0
               1963  62420208.0
               1964  60977008.0
               1965  60379266.0
...                         ...
Yield          2016     86142.0
               2017     82812.0
               2018     81961.0
               2019     80056.0
               2020     81750.0

[180 rows x 1 columns]

In [33]:
a[a["Value"] > 6.076251e+07].groupby(["Element", "Year"]).mean()

                           Value
Element        Year
Area harvested 1961   64869558.0
               1963   62420208.0
               1964   60977008.0
               1966   61141626.0
               1967   65847777.0
...                          ...
Production     2016  503466147.0
               2017  440272862.0
               2018  439711070.0
               2019  420873484.0
               2020  434875197.0

[90 rows x 1 columns]